// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

#include "friend.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace biz {
class GetFriendListsReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetFriendListsReq>
      _instance;
} _GetFriendListsReq_default_instance_;
class GetFriendListsAckDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetFriendListsAck>
      _instance;
} _GetFriendListsAck_default_instance_;
}  // namespace biz
namespace protobuf_friend_2eproto {
static void InitDefaultsGetFriendListsReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biz::_GetFriendListsReq_default_instance_;
    new (ptr) ::biz::GetFriendListsReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biz::GetFriendListsReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetFriendListsReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetFriendListsReq}, {}};

static void InitDefaultsGetFriendListsAck() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::biz::_GetFriendListsAck_default_instance_;
    new (ptr) ::biz::GetFriendListsAck();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::biz::GetFriendListsAck::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetFriendListsAck =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetFriendListsAck}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GetFriendListsReq.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetFriendListsAck.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::biz::GetFriendListsReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::biz::GetFriendListsReq, uid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::biz::GetFriendListsAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::biz::GetFriendListsAck, result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::biz::GetFriendListsAck, friends_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::biz::GetFriendListsReq)},
  { 6, -1, sizeof(::biz::GetFriendListsAck)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::biz::_GetFriendListsReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::biz::_GetFriendListsAck_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "friend.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014friend.proto\022\003biz\" \n\021GetFriendListsReq"
      "\022\013\n\003uid\030\001 \001(\r\"4\n\021GetFriendListsAck\022\016\n\006re"
      "sult\030\001 \001(\005\022\017\n\007friends\030\002 \003(\0142T\n\020FriendSer"
      "viceRpc\022@\n\016GetFriendLists\022\026.biz.GetFrien"
      "dListsReq\032\026.biz.GetFriendListsAckB\003\200\001\001b\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 206);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "friend.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_friend_2eproto
namespace biz {

// ===================================================================

void GetFriendListsReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetFriendListsReq::kUidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetFriendListsReq::GetFriendListsReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_friend_2eproto::scc_info_GetFriendListsReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:biz.GetFriendListsReq)
}
GetFriendListsReq::GetFriendListsReq(const GetFriendListsReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  uid_ = from.uid_;
  // @@protoc_insertion_point(copy_constructor:biz.GetFriendListsReq)
}

void GetFriendListsReq::SharedCtor() {
  uid_ = 0u;
}

GetFriendListsReq::~GetFriendListsReq() {
  // @@protoc_insertion_point(destructor:biz.GetFriendListsReq)
  SharedDtor();
}

void GetFriendListsReq::SharedDtor() {
}

void GetFriendListsReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetFriendListsReq::descriptor() {
  ::protobuf_friend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_friend_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetFriendListsReq& GetFriendListsReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_friend_2eproto::scc_info_GetFriendListsReq.base);
  return *internal_default_instance();
}


void GetFriendListsReq::Clear() {
// @@protoc_insertion_point(message_clear_start:biz.GetFriendListsReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uid_ = 0u;
  _internal_metadata_.Clear();
}

bool GetFriendListsReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:biz.GetFriendListsReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 uid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:biz.GetFriendListsReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:biz.GetFriendListsReq)
  return false;
#undef DO_
}

void GetFriendListsReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:biz.GetFriendListsReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->uid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:biz.GetFriendListsReq)
}

::google::protobuf::uint8* GetFriendListsReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:biz.GetFriendListsReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->uid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biz.GetFriendListsReq)
  return target;
}

size_t GetFriendListsReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biz.GetFriendListsReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 uid = 1;
  if (this->uid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetFriendListsReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biz.GetFriendListsReq)
  GOOGLE_DCHECK_NE(&from, this);
  const GetFriendListsReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetFriendListsReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biz.GetFriendListsReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biz.GetFriendListsReq)
    MergeFrom(*source);
  }
}

void GetFriendListsReq::MergeFrom(const GetFriendListsReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biz.GetFriendListsReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uid() != 0) {
    set_uid(from.uid());
  }
}

void GetFriendListsReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biz.GetFriendListsReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetFriendListsReq::CopyFrom(const GetFriendListsReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biz.GetFriendListsReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetFriendListsReq::IsInitialized() const {
  return true;
}

void GetFriendListsReq::Swap(GetFriendListsReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetFriendListsReq::InternalSwap(GetFriendListsReq* other) {
  using std::swap;
  swap(uid_, other->uid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetFriendListsReq::GetMetadata() const {
  protobuf_friend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_friend_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetFriendListsAck::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetFriendListsAck::kResultFieldNumber;
const int GetFriendListsAck::kFriendsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetFriendListsAck::GetFriendListsAck()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_friend_2eproto::scc_info_GetFriendListsAck.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:biz.GetFriendListsAck)
}
GetFriendListsAck::GetFriendListsAck(const GetFriendListsAck& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      friends_(from.friends_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:biz.GetFriendListsAck)
}

void GetFriendListsAck::SharedCtor() {
  result_ = 0;
}

GetFriendListsAck::~GetFriendListsAck() {
  // @@protoc_insertion_point(destructor:biz.GetFriendListsAck)
  SharedDtor();
}

void GetFriendListsAck::SharedDtor() {
}

void GetFriendListsAck::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetFriendListsAck::descriptor() {
  ::protobuf_friend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_friend_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetFriendListsAck& GetFriendListsAck::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_friend_2eproto::scc_info_GetFriendListsAck.base);
  return *internal_default_instance();
}


void GetFriendListsAck::Clear() {
// @@protoc_insertion_point(message_clear_start:biz.GetFriendListsAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  friends_.Clear();
  result_ = 0;
  _internal_metadata_.Clear();
}

bool GetFriendListsAck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:biz.GetFriendListsAck)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes friends = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_friends()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:biz.GetFriendListsAck)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:biz.GetFriendListsAck)
  return false;
#undef DO_
}

void GetFriendListsAck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:biz.GetFriendListsAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // repeated bytes friends = 2;
  for (int i = 0, n = this->friends_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->friends(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:biz.GetFriendListsAck)
}

::google::protobuf::uint8* GetFriendListsAck::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:biz.GetFriendListsAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // repeated bytes friends = 2;
  for (int i = 0, n = this->friends_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(2, this->friends(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:biz.GetFriendListsAck)
  return target;
}

size_t GetFriendListsAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:biz.GetFriendListsAck)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated bytes friends = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->friends_size());
  for (int i = 0, n = this->friends_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->friends(i));
  }

  // int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetFriendListsAck::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:biz.GetFriendListsAck)
  GOOGLE_DCHECK_NE(&from, this);
  const GetFriendListsAck* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetFriendListsAck>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:biz.GetFriendListsAck)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:biz.GetFriendListsAck)
    MergeFrom(*source);
  }
}

void GetFriendListsAck::MergeFrom(const GetFriendListsAck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:biz.GetFriendListsAck)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  friends_.MergeFrom(from.friends_);
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void GetFriendListsAck::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:biz.GetFriendListsAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetFriendListsAck::CopyFrom(const GetFriendListsAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:biz.GetFriendListsAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetFriendListsAck::IsInitialized() const {
  return true;
}

void GetFriendListsAck::Swap(GetFriendListsAck* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetFriendListsAck::InternalSwap(GetFriendListsAck* other) {
  using std::swap;
  friends_.InternalSwap(CastToBase(&other->friends_));
  swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetFriendListsAck::GetMetadata() const {
  protobuf_friend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_friend_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

FriendServiceRpc::~FriendServiceRpc() {}

const ::google::protobuf::ServiceDescriptor* FriendServiceRpc::descriptor() {
  protobuf_friend_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_friend_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* FriendServiceRpc::GetDescriptor() {
  return descriptor();
}

void FriendServiceRpc::GetFriendLists(::google::protobuf::RpcController* controller,
                         const ::biz::GetFriendListsReq*,
                         ::biz::GetFriendListsAck*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method GetFriendLists() not implemented.");
  done->Run();
}

void FriendServiceRpc::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_friend_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      GetFriendLists(controller,
             ::google::protobuf::down_cast<const ::biz::GetFriendListsReq*>(request),
             ::google::protobuf::down_cast< ::biz::GetFriendListsAck*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& FriendServiceRpc::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::biz::GetFriendListsReq::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& FriendServiceRpc::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::biz::GetFriendListsAck::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

FriendServiceRpc_Stub::FriendServiceRpc_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
FriendServiceRpc_Stub::FriendServiceRpc_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
FriendServiceRpc_Stub::~FriendServiceRpc_Stub() {
  if (owns_channel_) delete channel_;
}

void FriendServiceRpc_Stub::GetFriendLists(::google::protobuf::RpcController* controller,
                              const ::biz::GetFriendListsReq* request,
                              ::biz::GetFriendListsAck* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace biz
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::biz::GetFriendListsReq* Arena::CreateMaybeMessage< ::biz::GetFriendListsReq >(Arena* arena) {
  return Arena::CreateInternal< ::biz::GetFriendListsReq >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::biz::GetFriendListsAck* Arena::CreateMaybeMessage< ::biz::GetFriendListsAck >(Arena* arena) {
  return Arena::CreateInternal< ::biz::GetFriendListsAck >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
